### ISSUE TITLE
attributes created by intake-esm contain illegal characters

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xscen#13]
`intake-esm` creates global attributes based on the catalog. By default, they follow the format: `intake_esm_attr/(x)`. 

However, `/` is an illegal character when, in xarray, `engine="netcdf4"`. We have no control over that character, and so this will need a fix in `intake_esm` itself. In the meantime, a fix is needed in `xscen` too.

**Comment by aulemahal** [comment]
See intake/intake-esm#490.

**Comment by aulemahal** [comment]
See intake/intake-esm#509
It will solve this and thus break xscen!
