### ISSUE TITLE
tiny detail in delta attrs

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/xscen#193]
https://github.com/Ouranosinc/xscen/blob/2f8d143997b00f935590e792b133a0aedce0ce8b/xscen/aggregate.py#L263

This is really a small issue, but in the description and long_name of delta, I would prefer a "-", not a "_".

**Comment by RondeauG** [comment]
Sure. I honestly don't remember why we did that. Maybe to separate the periods more clearly?

**Comment by RondeauG** [comment]
Fixed by #228.
