### ISSUE TITLE
Incorrect behaviour of subset_file_coverage when multiple files are in range

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xscen#226]
### Setup Information

- xscen version: 0.6.12

### Description

Since the recent change, `catalog.subset_file_coverage` fails when multiple files are located within the interval, because `guessed_length` results in multiple values instead of just one:

```
guessed_length = pd.IntervalIndex.from_arrays(
                intervals[files_in_range].map(
                    lambda x: max(x.left, period_interval.left)
                ),
                intervals[files_in_range].map(
                    lambda x: min(x.right, period_interval.right)
                ),
            ).length
```

Which gives:
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

### Steps To Reproduce

Search for multiple years of CRCM5 data (which is saved monthly).

### Additional context

Applying `sum(guessed_length, datetime.timedelta())` will make the line `guessed_length / period_length < coverage` work as intended.

Found by @vindelico 

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

**Comment by aulemahal** [comment]
Can we get a MWE of the bug with a traceback ? 

It does not happen on my side.

```python3
import xscen as xs

cat = xs.DataCatalog('MRCC5-disponible.json')
res = cat.search(code='bby', periods=['1950', '1990'])
```
This works.
