### ISSUE TITLE
reverse_format has limitations

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xscen#24]
### Generic Issue

When I write a pattern like "{variable}_{*}_{date_start}.nc", I would like `reverse_format` to fit "pr_gn_2020.nc", but not "pr_v234_gn_2021.nc". Sadly, this is not how it is written and in the second case, `date_start` will be "gn_2021", which breaks everything. 
One solution would be to add as many "{*}" as there are unneeded sections, but that's the point : I don't know. 
My wanted solution would be to forbid the '_' (and '/' and '-') characters in "{*}".

Not sure it would be feasible to fix this in `intake` so maybe there is a better tool somewhere? (like readable regex).

**Comment by juliettelavoie** [comment]
I don't think we want to forbid '-' because that can be in the name of sources.

**Comment by aulemahal** [comment]
True! The only place we use it is between `date_start` and `date_end`, so if we ever get to a point where the reverse format is stronger, we could resuscitate Trevor's PR.
