### ISSUE TITLE
Double preprocess in catalog.to_dataset()

### ISSUE THREAD

**Issue by sarahclaude** [Ouranosinc/xscen#245]
### Setup Information

- xscen version: v.0.7.1
- Python version: 3.10

### Description

When using preprocess with Datacatalog.to_dataset() I get the error:
TypeError: intake_esm.core.esm_datastore.to_dask() got multiple values for keyword argument 'preprocess' 
linked to  xscen/catalog.py", line 458, in to_dataset
    ds = cat.to_dask(preprocess=preprocess, **kwargs)

### Steps To Reproduce
```
def preprocess(ds):
    return ds

dataset = catalog.to_dataset(preprocess=preprocess)
```

### Additional context

Preprocess is sent two times to intake esmf

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

**Comment by aulemahal** [comment]
Dang. 

This line: 
https://github.com/Ouranosinc/xscen/blame/7fa182831f7eb38c4ac4c183613319d38a7cadae/xscen/catalog.py#L414
should be a `.pop`.
