### ISSUE TITLE
Reduce the size of /docs

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xscen#247]
### Generic Issue

* xscen version: 0.7.1

### Description
These two files/directories are currently pretty big and don't need to be.

- /docs/notebooks/samples/tutorial/ : ~ 8Mb
  - The files are already fairly small (4x4x18600, 1.3 Mb each), but could be reduced even further along the `time` axis.
- /docs/notebooks/samples/pangeo-cmip6.csv : ~ 8Mb. 
  - This is basically only used once to show the advanced search features of `search_data_catalogs`. We don't need 35 000 assets to do that.

**Comment by Zeitsperre** [comment]
Can the pangeo-cmip6.csv be fetched from somewhere online? It's not the best practice (for PANGEO), but maybe we can simply point the test to that location?

**Comment by RondeauG** [comment]
Sadly not. It's based on an online version, but modified so the columns match ours.
