### ISSUE TITLE
no more nans in the water on feb 29th after `clean_up`

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/xscen#29]
### Generic Issue

There is an issue with the convert_calendar option of `clean_up`.

For missing days filled with a float (eg. 0 mm), the full domain is filled with 0s. No more nans over the water.

If 'stack_drop_nan' is used, this is fixed by switching the order of the unstack and the convert_calendar ( I did this in #28). But for people not using that option, it will be a problem. Should we add an arg to pass a mask or create a mask ourselves in `clean_up` or something else?

**Comment by RondeauG** [comment]
We should manage that, yes. 

I think we could do something like : 
```
mask_args = {'mask_nans': True}
mask = regridding.create_mask(ds=ds_copy[v].isel(time=0), mask_args=mask_args)
ds_copy[v] = ds_copy[v].where(mask==1)
```

**Comment by RondeauG** [comment]
Actually looking at the code, this is an `xclim` issue, not `xscen`. Could you create an Issue there as well?

**Comment by RondeauG** [comment]
Copy-pasting the solution from the Slack channel:
```
ocean = da_in.isnull().all('time')
out = convert_calendar(da_in, ..., missing=0).where(~ocean)
```

**Comment by RondeauG** [comment]
@juliettelavoie This can be closed, right?
