### ISSUE TITLE
Implement ensemble analyses

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xscen#3]
### Description

Some ideas:

- Ensemble statistics (ensemble mean, spread, change vs. historical, etc.). A lot already exists in `xclim.ensemble`.
- Projections in T° change vs. preindustrial levels

Here too, most of the work should be done within `xclim`, with `xscen` acting as a wrapper.

**Comment by juliettelavoie** [comment]
I am working on this, but I am not sure what you mean by "change vs. historical"  in the first bullet point?

For the second bullet point, are you talking of showing results by level of global warming ? like creating a ensemble that is the right 30 years for a given warming level for each model ?

**Comment by RondeauG** [comment]
It's been a while, but I think "change vs. historical" was meant for all the analyses and statistics we might want to do during a comparison between the historical and future period.

The second point was open-ended, in the sense that we might want to develop tools and functions to help facilitate doing projections by warming level.

**Comment by juliettelavoie** [comment]
Ok, I think the first point might not be a priority for now...

For warming levels, do you want me to work on a xscen function that helps with that or are you already doing that ?

**Comment by RondeauG** [comment]
I'm already working on something for warming levels. I think it'll give us a good understanding of what's needed in xscen, xclim or the workflow itself. In other words, that can wait too.
