### ISSUE TITLE
Exists_in_cat returns True with missing variable

### ISSUE THREAD

**Issue by sarahclaude** [Ouranosinc/xscen#37]
### Setup Information

- xscen version: 0.2.1
- Python version: 3.9.13

### Description

DataCatalog.exists_in_cat() returns True if one the variable is in the catalog and the others are missing.
@juliettelavoie 

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

**Comment by juliettelavoie** [comment]
`exists_in_cat` uses the `search` function of intake ESM. It only checks if search finds at least one dataset with the arguments given. 
`search` looks for all dataset that include at least one of the variable you give it. To restrict that, you can pass `require_all_on` to `exists_in_cat` in the same way that you would pass it to `search`.

eg.

`pcat.exists_in_cat(require_all_on=['id','processing_level'],
            processing_level='extracted',
            id='CMIP6_ScenarioMIP_CSIRO-ARCCSS_ACCESS-CM2_ssp245_r1i1p1f1_global',
            variable=['tasmax', 'tasmin', 'pr'])`
