### ISSUE TITLE
Add <= pin on xclim

### ISSUE THREAD

**Issue by SarahG-579462** [Ouranosinc/xscen#399]
### Addressing a Problem?

When xclim updates with breaking changes, this can sometimes break xscen (e.g. today, with xscen at 0.8.3 on conda-forge and xclim at 0.49.0). Since the packages are so tightly linked, it seems very likely that this will often occur.

### Potential Solution

Add xclim <= test-version (and potentially xclim >= functioning version) pins in environment.yml

### Additional context

Annoyingly my apps broke while this bug was occuring, but because the delay on this version release is around 3 hours, it's not worth fixing in my git repo.

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

**Comment by Zeitsperre** [comment]
I would go one step further and try installing the lowest pinned versions of a library to determine what our actual range of supported versions is.

There's an ongoing discussion about adding this functionality into `pip` (https://github.com/pypa/pip/issues/8085), but apparently there's something in both `uv` and `pdm` that does exactly that.
