### ISSUE TITLE
Raise the version for installed Cartopy

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xscen#401]
`cartopy` has been under LGPLv3 up until very recently. Although this license critically allows for linking (unlike GPLv3), this is causing a stink for the newly-integrated FOSSA license scanner.

They recently adopted BSD's 3-Clause license (and also dropped support for Python3.9) and I would like to manually add a pin for Python3.10+ to use this version or later only.

For more information: https://github.com/SciTools/cartopy/pull/2285

**Comment by RondeauG** [comment]
I guess that we were about to leave 3.9 behind anyway, so I don't have anything against it.

**Comment by Zeitsperre** [comment]
Good news: They maintain support for Python3.9 with the new license. We don't need to drop that version just yet.

Will open a PR soon.
