### ISSUE TITLE
Automatic chunks for ensemble_stats

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/xscen#48]
### Generic Issue

By default, `xclim.ensembles.create_ensemble` creates huge chunks and so does `xscen.ensemble_stats`. This can be fixed by passing `create_kwargs= {'chunks': ...}`.

However, in xscen, we could maybe specify to take the chunks of the first dataset of the list by default if not given in `create_kwargs`.

(This issue came up when Dominic tried to use ensemble_stats but kept killing all his workers. )

**Comment by aulemahal** [comment]
> `xclim.ensembles.create_ensemble` creates huge chunks 

This happens when paths are passed to the function : it simply calls `xr.open_dataset` with the other kwargs.  In a normal workflow, wouldn't the datasets already be open (like with `to_dataset_dict`)?

Also, there is a mechanism in `ensemble_percentiles` to avoid the huge chunk problem, but it is very basic. It rechunks the array to have a single chunk along "realization", while increasing the number of chunks on another axis by the number of realizations, so in theory the chunksizes are conserved.

Mentioning it, in case it helps your debugging or gives ideas for solutions to implement here.

**Comment by juliettelavoie** [comment]
En effet, il passait une liste de paths avec `list(pcat.search(**search_dict).df.path)` parce que c'est mon exemple dans les docs. Est-ce que c'est plus efficace en général de passer `list(pcat.search(processing_level='regridded').to_dataset_dict().values())` ?

**Comment by aulemahal** [comment]
"plus efficace" je sais pas trop, mais comme dans le reste de `xscen` c'est au moment du `to_dataset_dict` que les arguments à `xr.open_dataset` sont passés (là et dans `extract_dataset` ), je dirais qu'il serait logique de faire ça ici aussi.
J'avais pas cliqué en regardant la PR sur les ensembles, mais il pourrait être intéressant que la fonction d'xscen prennent en entrée le dataset dict? Ça permetterait peut-être de peupler la coordoonnée "realization" avec les "id"?

**Comment by juliettelavoie** [comment]
oh intéressant! Sauf que le output de `ensemble_stats` est toujours une statistique sur l'ensemble (ou en tout cas le résultats d'une fonction xclim.ensembles). Donc la dimension `realisation` est toujours collapse, je pense. On ne gagne pas vraiment à changer le nom des réalisations pour les ids.

J'aime quand même l'idée d'accepter aussi un dictionnaire, en plus d'une liste.

**Comment by aulemahal** [comment]
Ah oui t'as raison! 
Je pense que @RondeauG  avait un cas de figure où la coordonnée "realization" pouvait être pertinente. Mais dans le fond, c'est peut-être plus xclim qu'il faut éditer...

**Comment by RondeauG** [comment]
La coordonnée `realisation` va très probablement devenir pertinente quand on va implémenter le clustering, oui.

**Comment by juliettelavoie** [comment]
le clustering tu veux dire pour le ensemble selection ? est-ce que tu utilises `ensemble_stats` pour  ça ?

Peut-être que les ids sont utiles dans les weighted stats, mais là aussi il me semble que c'est plus xclim que xscen.

**Comment by RondeauG** [comment]
Ah c'est vrai, ça va être ailleurs. Cela dit oui, il y a potentiellement de quoi avec les statistiques pondérées. Je ne pense pas que ça soit urgent, mais c'est assez simple d'implémenter `to_dataset_dict()` dans `ensemble_stats`

**Comment by juliettelavoie** [comment]
en effet, je pense qu'on ne perd rien à accepter un dict dans `ensemble_stats`. Je peux le rajouter dans ma prochaine PR.

**Comment by aulemahal** [comment]
Et voilà : xclim#1153
