### ISSUE TITLE
resample MS on 360_day doesn't work properly

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/xscen#53]
### Generic Issue

Lorsqu'on fait un resampling MS à partir de données journalières sur un calendrier 360_day avec `search_data_catalogs`. La dimension temps est au 16e jour au lieu du 1er jour.

exemple:
```
test = xs.search_data_catalogs(
    data_catalogs=[path],
    variables_and_freqs= {'tasmax':'MS'},
          match_hist_and_fut= True,
          allow_conversion= True,
          allow_resampling= True,
         periods=['2010', '2020'],
          other_search_criteria={'experiment':'ssp585', 'source':'KACE-1-0-G'}
              )

for ind, dc in test.items():
    ds = xs.extract_dataset(catalog=dc)['MS']
    display(ds.time) 
```
donne:

array([cftime.Datetime360Day(2010, 1, 16, 0, 0, 0, 0, has_year_zero=True),
       cftime.Datetime360Day(2010, 2, 16, 0, 0, 0, 0, has_year_zero=True),...

**Comment by RondeauG** [comment]
Est-ce un bug `xscen` ou `xarray/pandas` ?

**Comment by juliettelavoie** [comment]
Pas sur, je ne connais pas assez bien le fonctionnement sur resampling xscen. Il faut que je regarde plus en profondeur pour comprendre.

**Comment by aulemahal** [comment]
Je fais l'hypothèse qu'il n'y a pas de resampling : 
`simulation/raw/CMIP6/ScenarioMIP/global/NIMS-KMA/KACE-1-0-G/ssp585/r1i1p1f1/mon/tasmax/tasmax_Amon_KACE-1-0-G_ssp585_r1i1p1f1_gr_20150101-21001230.nc` existe et a une coordonnée temps tel que tu la vois.

Ceci serait donc plutôt un manque dans xscen : on devrait appeler une sorte de  `reindex` si le `infer_freq` est différent de la freq demandée.

**Comment by juliettelavoie** [comment]
Oh! Je n'avais pas réalisé que tasmax monthly existait dans nos fichiers! En fait, c'est seulement avec ce modèle à cause d'une erreur dans les attributs du fichier (https://github.com/Ouranosinc/miranda/issues/47 )

**Comment by juliettelavoie** [comment]
Quand j'ai crée mon dataCatalog, j'ai lu la fréquence (mon) dans le path et automatiquement xscen a rempli la colonne xrfreq avec MS, même si ce n'est pas vraiment le cas! Le problème se situe donc dans `frequency_to_xrfreq.json`. Le mapping "mon: MS" n'est pas toujours vrai. Ensuite, `search_data_catalog` a juste crut mon DataCatalog qui lui a dit que c'était MS.

deux idées:
1. Avoir xrfreq dans le path au lieu de frequency, mais ça serait quand même un gros effort.
2. Ne pas remplir xrfreq automatiquement à partir de frequency. Obliger parse_directory à lire le fichier pour avoir xrfreq lorsqu'il y a ambivalence possible.

**Comment by aulemahal** [comment]
Je suis quand même d'accord, mais j'ai aussi déjà eu des données quotidiennes qui étaient données à midi. Ce qui me fait dire, c'est quoi un cas ambigu d'abord?

Une option 3: Jusqu'au `extract_dataset`, considérer `xrfreq` comme étant autant imprécis que `frequency`. Dans le `extract`, ajouter un check comme fait par `create_ensemble`:
https://github.com/Ouranosinc/xclim/blob/4b53245f25352d0ace821b6bddb511480e2f61ff/xclim/ensembles/_base.py#L381-L388
(ici `resample_freq` serait la valeur dans `variable_and_freqs`)

J'ai l'impression que le 2 va être compliqué parce que les  `xrfreq` restent limités. Exemple, une fréquence mensuelle donnée au 15e du mois, ça n'existe pas dans cette syntaxe.

**Comment by RondeauG** [comment]
Est-ce qu'on pourrait chercher le timestep le plus près de ce qui a été demandé, mais obligatoirement passer par un resampling peu importe si c'est déjà ou non à la fréquence voulue?

**Comment by juliettelavoie** [comment]
Bon point Pascal qu'on aura toujours des temps bizarres, non couvert pas xrfreq. Je pense que dans le long terme, lorsqu'on réécrira les données en zarr, on pourra directement mettre une dimension temps standard.

 En attendant, oui, je pense que c'est une bonne idée de faire un resampling obligatoire.

**Comment by RondeauG** [comment]
J'ai l'impression que ce problème a été réglé avec `ensure_correct_time`? On peut fermer ?
@aulemahal @juliettelavoie

**Comment by juliettelavoie** [comment]
oui
