### ISSUE TITLE
pass coords to unstack_fill_nan

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/xscen#59]
### Generic Issue

`xs.properties_and_measures` has an argument boolean `unstack` to activate `unstack_fill_nan` (with default None `coords`) . I thought the `coords` argument of `unstack_fill_nan` was not necessary. Turns out it is necessary if you have a line of all nans.

So, we need to pass the `coords` argument to `xs.properties_and_measures`  in order to use `unstack_fill_nan` properly. This is annoying because the path of coords will change with the region (can't write the path directly in the config) and make a messier workflow.

2 possible solutions:

1. `unstack` boolean become a string argument where we pass `coords`. And there is a bit of messing around in the workflow to give the path to the right `coords`. (or something similar to `maybe_unstack_dict` in `xs.clean_up`)
2. Better defaults in the stack and unstack functions:
Default `stack_drop_nans` `to_file`arg and and `unstack_fill_nan` `coords` arg become f"coords_{ds.attrs['cat:domain']}.nc}. This way the workflow is more clean.

**Comment by aulemahal** [comment]
If this was my own code, I'd go with n°1. But we're trying to be a bit more foolproof then that...

In a "single-workflow" mindset, I guess n°2 makes sense? If `stack_drop_nans`'s `to_file` can be a folder, then the config can set a single folder where all the "coords" file end up? I'd say that  `domain` might not be enough to uniquely identify the set? For safety, I'd suggest adding something simple like the shape of the initial grid? (kinda the same safety level as xESMF's weights).

**Comment by juliettelavoie** [comment]
What do you mean by the shape of the initial grid ? Like the id of the initial dataset ?

The issue here is when we try to unstack a simulation we don't have that info in the global attrs.
* For the reference:
  * stack: use cat:domain and cat:id for `to_file`
  * unstack: use cat:domain and cat:id for `coords`

* For simulation: 
  * stack (we never actually do this, it is done in the regrid)
  * unstack: we can use cat:domain, but we don't have a trace of the ds_ref's id in ds_sim attrs.


The info about the grid is supposed to be in `domain` (like for 44i, 22i,...). I think domain should uniquely identify a set.

**Comment by aulemahal** [comment]
I meant something like "550x949". 

I fear `domain` is not unique enough to distinguish between grids. Your example is exactly the one I struggled with : `NAM-44` only means that the overall grid resolution is 0.44°. Some models are RotatedPole, some are Cartesian or Lamber Conformal or what not, they have really different grids!

But, we could force ourselves to have a unique mapping between grids and domains _after_ the regrid step? Then using `cat:domain` would make sense. My suggestion of adding the grid size is merely a safeguard for when an error has been made and the mapping is not unique anymore.

**Comment by juliettelavoie** [comment]
I see your point. 
Still, the point is for `unstack` to be able to guess the path of `coords` only with info inside ds_stack.

I guess, we could have `extract` put `domain = f"{region_name}_{shape}"`... This would be transfered automatically when doing the regridding.

Do you have a better idea to where else to store the info about the grid?

**Comment by aulemahal** [comment]
> to be able to guess the path of coords only with info inside ds_stack.

ah oui, c'est vrai, damned...

I'm not a fan of automatically adding the shape to the domain name (it then becomes different from what the user asked). 

Is it too dangerous to add an "original_shape" attribute to the dimension created by `stack_drop_nans` ?
I believe it would be preserved even through a regrid with the latest version of xESMF, but I'm not sure.

**Comment by juliettelavoie** [comment]
idée intéressante je vais explorer ça!

**Comment by juliettelavoie** [comment]
zarr doesn't like multindex so the coord is drop when save to zarr. If we give is an attrs, zarr doesn't drop it and we get `NotImplementedError: variable None is a MultiIndex, which cannot yet be serialized to netCDF files (https://github.com/pydata/xarray/issues/1077). Use reset_index() to convert MultiIndex levels into coordinate variables instead.`

Maybe we can put the original_shape attrs in lat or lon instead.
