### ISSUE TITLE
slightly different latitudes for historical and ssp breaks extract

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/xscen#62]
### Generic Issue

I am not sure if this is a problem that should be fixed by xscen or by fixing the file.

For EC-Earth3 r3i1p1f1 historical, the latitudes are cut shorter than for EC-Earth3 r3i1p1f1 ssp585, EC-Earth3 r1i1p1f1 historical and EC-Earth3 r1i1p1f1 585 (these 3 have exactly the same latitudes).

eg. -88.76695 vs -88.76695135.

The difference is really small, but big enough that is breaks `extract` when it try to `combine_by_coords`. It thinks some lat are the same and some are different and gives an error:

`ValueError: Resulting object does not have monotonic global indexes along dimension lat`

I am able to combine them manually if I round both latitudes, but this does not fit into xscen very well and is not a universal solution.

Do you have an idea how to handle cases like that in xscen?

Or is it more a case of rewritting the file manually with the right latitudes ?

**Comment by RondeauG** [comment]
This used to be fixed by xscen's predecessor, but we decided that it should be fixed beforehand instead of applying a band-aid. The actual issue is that we don't have a proper place to report these problems...

Tagging @Zeitsperre.

**Comment by juliettelavoie** [comment]
I think miranda is the place to report. Will copy there.

**Comment by Zeitsperre** [comment]
Yes, definitely an issue for pre-production. It's becoming clear that we need a way to coordinate and divide tasks/effort between xclim/xscen/miranda. Something to discuss at our next meeting.

**Comment by juliettelavoie** [comment]
maybe we need more than Trevor to have write access to /datasets to help with those issue.

**Comment by Zeitsperre** [comment]
I wouldn't mind the help, honestly, but I meant more a coordination of efforts to tackle some of the needs across repos (miranda: data conversion, cmip6 errata warnings, non-overlapping time periods, etc.). Some solutions for issues in xscen require work in other repos.

**Comment by juliettelavoie** [comment]
closing because this is a miranda thing now
