### ISSUE TITLE
Pass in-memory catalog to `search_data_catalogs`

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xscen#64]
### Addressing a Problem?

The current `search_data_catalog` re-opens the CSV files of the passed DataCatalog(s).
See: https://github.com/Ouranosinc/xscen/blob/6285df36e2fa5297d88871adee37ee6e9d26bdad/xscen/extract.py#L549-L560

The problem arises when on has made in-memory changes to the DataCatalog, which are not yet included in the csv. In the case of a ProjectCatalog, one can write the changes to disk, but even then, I find it non-intuitive.

### Potential Solution

I think I would make sense to use the dataframe(s) of the passed DataCatalog(s) instead of going back to the csvs.

### Additional context

I believe the current situation arises from the need to have a DataCatalog with a "registry" when `allow_conversion` is True. This might mean we would have to implement something to copy a DataCatalog while adding a registry.

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

**Comment by RondeauG** [comment]
I believe that this is mostly a legacy behaviour from when we used CSVs instead of DataCatalogs. If you can find a way to make it work without breaking `allow_conversion` or anything else, go ahead!
