### ISSUE TITLE
Checking that we have all years 

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/xscen#70]
### Generic Issue

simulation/raw/CMIP6/ScenarioMIP/global/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tasmax is missing years 2015-2019 but xscen didn't warn me of this or fail at any point. I figured it out because the diagnostics looked weird.

Should `search`/`extract` verify that all years are present in the period given or do we want miranda to do that check ?

**Comment by Zeitsperre** [comment]
I think it should be within `xscen` that a check like this happens.

There are cases where there are more years for some models/runs than others. Expectations would need to be coded for each case in `miranda`, whereas within `xscen`, ensuring that a timeseries is complete for the period of interest seems a lot more fitting (and simpler).

**Comment by RondeauG** [comment]
What did you do, exactly ? `_subset_file_coverage` should have caught that, but you might have found a bug.

**Comment by juliettelavoie** [comment]
```
cat_sim = xs.search_data_catalogs(
    data_catalogs=['dataCat_cmip6_2022-09-02.json'],
    variables_and_freqs= {'tasmax':'D'},
          match_hist_and_fut= True,
          allow_conversion= True,
          allow_resampling= False,
          periods= ['1956', '2100'],
          other_search_criteria={
            'experiment': 'ssp126', 'source':'FGOALS-g3'}
            )

ds_sim = xs.extract_dataset(catalog=cat_sim['CMIP6_ScenarioMIP_CAS_FGOALS-g3_ssp126_r1i1p1f1_global'],
                    periods= ['1956', '2100'])['D']
```

This returns a dataset with a whole.
