### ISSUE TITLE
Support French metadata

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xscen#79]
### Addressing a Problem?

Methods that come later in the workflow, such as the climatological mean or the deltas, modify metadata such as `long_name` to indicate what was done on the variable.

However, `xclim` can create French metadata, such as `long_name_fr`, which are being completely ignored and thus are not updated. We should fix that.

### Contribution

- [ ] I would be willing/able to open a Pull Request to contribute this feature.

**Comment by Zeitsperre** [comment]
Xclim potentially supports many more languages. If I can make a suggestion, the approach should be adaptable for generalized multilingual support (allow selection of language according to their [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) code).

**Comment by RondeauG** [comment]
Investigate i18n

**Comment by Zeitsperre** [comment]
For more context, see: https://github.com/Ouranosinc/pavics-sdi/issues/271
