### ISSUE TITLE
Catalogue avec de mauvaises dates

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/xscen#83]
### Generic Issue

- xscen version: '0.3.16-beta'
- Python version: 3.9.10
- Operating System: mac

### Description
Pour les expériences piControl qui ont des dates autour de l'an 0, on devine mal les date_start et date_end.
Par exemple,  `tasmax_day_GFDL-ESM4_piControl_r1i1p1f1_gr1_00810101-01001231.nc` devrait être de 0081-01-01 à 0100-0101, mais `parse_directory` nous donne 1981-01-01 00:00 à  100-12-31 00:00. Dans ce cas, ça brise à l'extract parce que end< start, mais il y a aussi des plus sneaky qui ne se font pas détecter. En plus, la majorité des dates devinées sont correctes,  il y en a juste quelques unes qui sont problématiques.

Je n'ai pas encore regarder le code en profondeur pour voir d'où vient le problème.

### What I Did
```
dataCat_sim = parse_directory(
            directories=path_sim,
            globpattern='*.nc',
            patterns=[
                "{activity}/{domain}/{institution}/{source}/{experiment}/{member}/{frequency}/{variable}/{*}_{*}_{*}_{*}_{*}_{*}_{date_start}-{date_end}.nc",
            ],
            read_from_file= False,
            homogenous_info={
                'type':'simulation',
                'processing_level':'raw',
                'mip_era': 'CMIP6'
            },
            xr_open_kwargs={'drop_variables': ['time_bnds', 'lat_bnds', 'lon_bnds', 'height']}
        )

```

**Comment by aulemahal** [comment]
Est-ce que l'erreur apparaissant dans `dataCat_sim` directement ou bien dans le catalogue une fois écris sur disque puis réouvert?

Mes tests très simples me montrent que:
-  si la date dans le nom de fichier a bien une année sur 4 caractères :
    - `xscen.catalog.date_parser` (et donc `datetime.strptime`) comprend bien les années avant 100 AD. 
    - Pareillement pour `pd.Period`
- `df.to_csv` écrit les dates SANS les 0 devant l'année.
    - À la relecture du catalogue, les années avant 100 sont comprises comme "%y" et non "%Y", c'est à dire que y < 69 -> 19XX et y >= 69 -> 20XX.

Donc, si c'est ce que j'ai observé, ça demanderait un argument spécial pour le `to_csv` et ce n'est pas xscen qui l'a fait ici. Mais il faudrait s'assurer que ça se fasse dans intake-esm (et dans `ouranos_data_catalog`).

**Comment by aulemahal** [comment]
Lol, je suis tombé dans le trou et j'ai finalement trouvé le bogue (encore une fois si l'erreur est celle que j'ai mentionnée ci-haut).

Solution pour @juliettelavoie : Exécuter le `to_csv` sur ton mac.

https://stackoverflow.com/a/43633945/9291575

Pandas utilise "%Y-%m-%d %H:00" comme format pour nos `Period`. Malgré la documentation de Python, qui mentionne bien ceci:
```
%Y | Year with century as a decimal number. | 0001, 0002, …, 2013, 2014, …, 9998, 9999
```
L'implémentation de `strftime` est en C et dépend de la plateforme. Sur Linux, %Y ne padde pas avec des 0. Sur Mac oui.

Solution:  utiliser "%4Y".
```python3
df_str = df.copy()
df_str['date'] = df.date.dt.strftime("%4Y-%m-%d %H:00")
df_str.to_csv('...')
```

**Comment by juliettelavoie** [comment]
En effet, directement `dataCat_sim` est correct et le problème apparait quand je lis le csv.

Tout mon setup est en remote deployment sur doris, donc avoir un mac ne me sauve pas vraiment ici.

J'essaie %4Y.

**Comment by juliettelavoie** [comment]
j'ai ajouter ton petit bout de code dans ProjectCatalog.update et tout semble réglé ! J'ouvre un PR sous peu.

**Comment by aulemahal** [comment]
J'ai ouvert un issue ici : https://github.com/pandas-dev/pandas/issues/48746
