### ISSUE TITLE
Use variable names for conversions, instead of the xclim indicator

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xscen#86]
### Generic Issue

* xscen version: 0.3.17

### Description
If I have a catalog with `tas` and `pr`, I would expect `prsn` to be found with `search_data_catalogs(allow_conversion=True, ...)`, but it's not. Instead, I need to search for `snowfall_approximation`. Once computed, the variable also appears as `snowfall_approximation` instead of `prsn` in the dataset`

Also, do we really want `allow_conversion=True` to be the default? I feel like this is something that should be a conscious choice.

**Comment by juliettelavoie** [comment]
Agreed that the default shouw be `allow_conversion=False`.

 Is `prsn` an official term ? Feels more like something that should be changed in xclim maybe ?

**Comment by RondeauG** [comment]
Yes, `prsn` stands for `snowfall_flux`. The issue was that CF names were missing from the conversion YAML. See #88

**Comment by aulemahal** [comment]
Pour préciser, ça s'appelle "snowfall_approximation" dans xclim parce que c'est pas mal une approximation!

Mais si on utilise l'indicateur de base, la variable va s'appeler `prsn`. Il faut répéter "var_name" explicitement dans un module virtuel, voilà la plupart du bogue.
