### ISSUE TITLE
More intuitive formatting for 'periods'

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xscen#87]
### Addressing a Problem?

`periods` is used across multiple functions in `xscen`, but it is not always easy to know which format is accepted or not. Sometimes `[start, end]` will work, sometimes it needs to be a list of lists `[[start, end]]`. Sometimes `int` works, sometimes `str` are required... It's honestly quite a mess that we should improve.

### Potential Solution

Support multiple formats (list & list of lists, int & str) for all functions that have a `periods` argument.

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

**Comment by juliettelavoie** [comment]
I think this is a good idea. 

If some functions really can't have many periods, depending on the function, we could have:
`period`: only 1 period accepted (only `[start, end]` accepeted)
or
`periods`: 1 or many ( `[start, end]`or  `[[start, end]]` accepted)

Are ints accepted has years or as index isel ?

**Comment by RondeauG** [comment]
I'd have to double-check, but I think `int` instances are simply converted to strings, then used in `.sel(time=slice(period[0], period[1]))`. It's just that this conversion is not always done (or bugged?) and will fail for some functions.

**Comment by juliettelavoie** [comment]
Mais pourquoi on fait le casting int to string? perso, j'irais pour accepter juste des strings comme xarray...

**Comment by RondeauG** [comment]
Ben, ça fait un peu partie du problème. `slice` utilise en effet juste des strings, mais nous on supporte parfois plus, parfois pas.

**Comment by juliettelavoie** [comment]
ok je vote pour ne jamais supporter, je trouve ça mélangeant pour rien.

**Comment by aulemahal** [comment]
Je sais pas si ça pourrait s'insérer ici, mais dans ma copie locale j'ai fais quelques modifs. J'avais besoin de changer le `coverage` dans `extract._subset_file_coverage`, mais l'argument est inacessible depuis `search_data_catalogs`. Faque j'ai ajouté une 3e élément à `period`. Si présent, c'est ce chiffre qui est utilisé comme `coverage`. 
Qu'en pensez-vous?

Les alternatives auxquelles j'ai pensé:
- Ajouter `coverage` comme argument de `search_data_catalogs`.
- Décorer `_subset_file_coverage` avec `@parse_config` pour pouvoir setter l'argument par la config.
- Baisser la valeur hardcodée.

**Comment by RondeauG** [comment]
C'est quoi, le 3e élément de `period`? Sinon, je crois que l'option 1 serait celle qui est la plus instinctive.

**Comment by juliettelavoie** [comment]
Moi aussi je préfère ajouter `coverage` comme argument.

**Comment by aulemahal** [comment]
Ben correct pour moi.  Ma technique avec `periods=[1981, 2010, 0.95]` permettait de ne rien modifier du tout dans `search_data_catalogs` (sauf la doc mettons). Mais c'est bien moins explicite, j'en conviens absolument.

Pour l'info, l'erreur venait de fichier du MRCC5 qui sont par mois. Notre utilisation de "Period(..., freq='H')" implique qu'un `date_end` de données quotidiennes (ou plus coarse) est à 23H. Sur ma période, pour chaque mois, il manquait 1h et ça a donné 96% de coverage.
