### ISSUE TITLE
Remove the intake_esm progress bar in extract_dataset

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xscen#95]
### Generic Issue

Each call to `to_dataset_dict` shows a progress bar in the output. It is sometimes useless and just noisy. It can be turned off with `to_dataset_dict(progressbar=False)`. 

Should we always remove it? Add an argument in `extract_dataset`? Have a logging-level dependent check?

**Comment by juliettelavoie** [comment]
Dans `extract_dataset`, je ferais `progressbar=False`. Mais le petit texte avec "key = id.processing...", je le mettrais dans les logs une seule fois. Ou minimalement dans la docstring.

**Comment by RondeauG** [comment]
Fixed with #144.
